apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/cluster-api-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cluster-api-operator
  namespace:  flux-system
spec:
  install:
    createNamespace: true
  targetNamespace: capi-system
  chart:
    spec:
      chart: cluster-api-operator
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: capi-operator
        namespace:  flux-system
      version: ${capi_operator_version:=v0.8.1}
  interval: 1m
  values:
    cert-manager:
      enabled: true