apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cluster-api-operated
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-api-operator
      namespace: flux-system
  chart:
    spec:
      chart: chart
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: github.com-danielr1996-helm-extra-deploy
        namespace: flux-system
  interval: 1m
  values:
    extraDeploy:
      - apiVersion: operator.cluster.x-k8s.io/v1alpha2
        kind: CoreProvider
        metadata:
          name: cluster-api
        spec:
          version: ${capi_core_version:=v1.6.1}
      - apiVersion: operator.cluster.x-k8s.io/v1alpha2
        kind: ControlPlaneProvider
        metadata:
          name: kubeadm
        spec:
          version: ${capi_core_version:=v1.6.1}
      - apiVersion: operator.cluster.x-k8s.io/v1alpha2
        kind: BootstrapProvider
        metadata:
          name: kubeadm
        spec:
          version: ${capi_core_version:=v1.6.1}
      - apiVersion: operator.cluster.x-k8s.io/v1alpha2
        kind: InfrastructureProvider
        metadata:
          name: hetzner
        spec:
          fetchConfig:
            url: "https://github.com/syself/cluster-api-provider-hetzner/releases/${capi_infrastructure_hetzner_version:=v1.0.0-beta.28}/infrastructure-components.yaml"
      - apiVersion: operator.cluster.x-k8s.io/v1alpha2
        kind: AddonProvider
        metadata:
          name: helm
        spec:
          version: ${capi_addonn_helm_version:=v0.1.1-alpha.0}


